### ISSUE TITLE
Error al descargar un Short YT

### ISSUE THREAD

**Issue by Mark0z1** [GabrielCastroV/youtube-downloader#1]
Que tal, recién instale tu aplicación, pero al pegar el enlace de un short de YT me marca el siguiente error, a que se debe?

![image](https://github.com/user-attachments/assets/5b74b771-075e-45fa-bb6d-c2e5c008bf66)

**Comment by GabrielCastroV** [comment]
Pronto tendrá la funcionalidad de descargar shorts, por los momentos solo videos tradicionales.
